name: match-tfe
services:
  postgres:
    container_name: database-matchtfe
    image: postgres:18-alpine
    restart: always
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - match_network

  authservice:
    container_name: authservice-matchtfe
    build:
      context: .
      dockerfile: ./authservice/Dockerfile
      target: development
    develop:
      watch:
        - action: rebuild
          path: ./authservice/package.json

        - action: rebuild
          path: ./database/package.json

        - action: sync
          path: ./authservice
          target: /usr/src/authservice
          ignore:
            - node_modules

        - action: sync
          path: ./database
          target: /usr/src/database
          ignore:
            - node_modules
    depends_on:
      - postgres
    networks:
      - match_network
    env_file:
      - .env
  
  userservice:
    container_name: userservice-matchtfe
    build:
      context: .
      dockerfile: ./userservice/Dockerfile
      target: development
    develop:
      watch:
        - action: rebuild
          path: ./userservice/package.json

        - action: rebuild
          path: ./database/package.json

        - action: sync
          path: ./userservice
          target: /usr/src/userservice
          ignore:
            - node_modules

        - action: sync
          path: ./database
          target: /usr/src/database
          ignore:
            - node_modules
    depends_on:
      - postgres
    networks:
      - match_network
    env_file:
      - .env

  gatewayservice:
    container_name: gatewayservice-matchtfe
    build:
      context: .
      dockerfile: ./gatewayservice/Dockerfile
      target: development
    ports:
      - "8000:8000"
    develop:
      watch:
        - action: rebuild
          path: ./gatewayservice/package.json

        - action: sync
          path: ./gatewayservice
          target: /usr/src/gatewayservice
          ignore:
            - node_modules
    depends_on:
      - authservice
      - userservice
      - postgres
    networks:
      - match_network
    env_file:
      - .env

  webapp:
    container_name: webapp-matchtfe
    build: ./webapp
    develop:
      watch:
        - action: rebuild
          path: ./webapp/package.json
        
        - action: sync
          path: ./webapp
          target: /app
          ignore:
            - node_modules
    ports:
      - "3000:3000"
    networks:
      - match_network
    env_file:
      - .env

networks:
  match_network:
    driver: bridge

volumes:
  postgres_data: